# Container file for building a bootable container (bootc) for Raspberry Pi 4

FROM --platform=linux/arm64 quay.io/fedora/fedora-bootc:latest

# More dnf tuning, plus installing all the packages needed on the RPi
RUN dnf -y install \
       cockpit cockpit-ws cockpit-podman usbutils \
       git vim-enhanced tree \
       v4l-utils ffmpeg mpv \
       && \
    dnf clean all

ARG sshpubkey

# The useradd below doesn't seem to work ... <sad-trombone>
# This also sets up some necessary directories under /var/lib/squirrel-away
RUN if test -z "$sshpubkey"; then echo "must provide sshpubkey"; exit 1; fi; \
    useradd -G wheel core && \
    mkdir -m 0700 -p /home/core/.ssh && \
    echo $sshpubkey > /home/core/.ssh/authorized_keys && \
    chmod 0600 /home/core/.ssh/authorized_keys && \
    chown -R core: /home/core && \
    systemctl enable cockpit.socket && \
    systemctl mask systemd-remount-fs.service && \
    set -eu; mkdir -p /usr/ssh && \
    echo 'AuthorizedKeysFile /usr/ssh/%u.keys .ssh/authorized_keys .ssh/authorized_keys2' \
         >> /etc/ssh/sshd_config.d/30-auth-system.conf && \
    echo "${sshpubkey}" > /usr/ssh/root.keys && chmod 0600 /usr/ssh/root.keys

# Enables the Coral Edge TPU
# TODO: Add RUN command to make sure libedgetpu.so.1 file exists and include build instrutions if not
# TODO :: Can this be moved to the inferencing container?
COPY files/image-inference/usr/lib/edgetpu/libedgetpu.so.1 /usr/lib/edgetpu/libedgetpu.so.1

# Image capture script
COPY files/image-capture/script/squirrel-away-image-capture.sh /usr/local/bin/squirrel-away-image-capture.sh
RUN chmod +x /usr/local/bin/squirrel-away-image-capture.sh

# tmpfiles definition for cleaning images that are more than an hour old
# The squirrel-away-inference-cleanup.timer calls this tmpfile cleanup every hour
COPY files/image-inference/tmpfiles/* /etc/tmpfiles.d/

# Image capture unit file and timer ... enable the timer when this is all ready
COPY files/image-capture/systemd/* /etc/systemd/system/

# Image inferencing unit file, path watcher, and old image cleanup
COPY files/image-inference/systemd/* /etc/systemd/system/

# Enable necessary units (doesn't seem to work ?)
RUN systemctl enable squirrel-away-inference-image.path && \
    systemctl enable squirrel-away-inference-cleanup.timer && \
    systemctl enable squirrel-away-capture-image.timer

# Setup the squirrel-away-detector quadlet
COPY files/image-inference/quadlet/squirrel-away-detector.container /etc/containers/systemd/

# Directories needed by squirrel-away-detector
RUN mkdir -p /var/lib/squirrel-away/inference/{keep,garbage,input}

# Some test data for testing inferencing on the RPi
# Note the test data directory needs to be manually copied to the source directory
# TODO :: MOVE TO INFERENCING CONTAINER
# TODO :: DELETE
COPY files/testdata /usr/share/squirrel-away/testdata
